# Generated by Django 5.0.2 on 2024-03-17 07:20

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150, verbose_name="Name")),
                ("email", models.EmailField(max_length=150, verbose_name="Email")),
                ("subject", models.CharField(max_length=300, verbose_name="Subject")),
                ("message", models.TextField(max_length=2000, verbose_name="Message")),
                (
                    "created_at",
                    models.DateTimeField(auto_now=True, verbose_name="Date"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ContactFormMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=50)),
                ("email", models.CharField(blank=True, max_length=50)),
                ("subject", models.CharField(blank=True, max_length=150)),
                ("message", models.TextField(blank=True, max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("New", "New"),
                            ("Read", "Read"),
                            ("Closed", "Closed"),
                        ],
                        default="New",
                        max_length=10,
                    ),
                ),
                ("ip", models.CharField(blank=True, max_length=15)),
                ("notes", ckeditor_uploader.fields.RichTextUploadingField()),
                ("create_at", models.DateTimeField(auto_now_add=True)),
                ("update_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
