# Generated by Django 5.0.2 on 2024-03-17 07:31

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("base", "0002_contact_contactformmessage"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Contact",
        ),
    ]
